services:
  - type: web
    name: guesscasso-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT src.api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /
    autoDeploy: true 